#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TASK.Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="eInvoice")]
	public partial class DBContextDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertResponseMessage(ResponseMessage instance);
    partial void UpdateResponseMessage(ResponseMessage instance);
    partial void DeleteResponseMessage(ResponseMessage instance);
    partial void InsertPrintConfig(PrintConfig instance);
    partial void UpdatePrintConfig(PrintConfig instance);
    partial void DeletePrintConfig(PrintConfig instance);
    partial void InsertPrint(Print instance);
    partial void UpdatePrint(Print instance);
    partial void DeletePrint(Print instance);
    partial void InsertBasePdf(BasePdf instance);
    partial void UpdateBasePdf(BasePdf instance);
    partial void DeleteBasePdf(BasePdf instance);
    partial void InsertHermesInvoiceDetail(HermesInvoiceDetail instance);
    partial void UpdateHermesInvoiceDetail(HermesInvoiceDetail instance);
    partial void DeleteHermesInvoiceDetail(HermesInvoiceDetail instance);
    partial void InsertInvoiceCancelCheck(InvoiceCancelCheck instance);
    partial void UpdateInvoiceCancelCheck(InvoiceCancelCheck instance);
    partial void DeleteInvoiceCancelCheck(InvoiceCancelCheck instance);
    partial void InsertHolidayConfig(HolidayConfig instance);
    partial void UpdateHolidayConfig(HolidayConfig instance);
    partial void DeleteHolidayConfig(HolidayConfig instance);
    partial void InsertInvoiceCheckQuery(InvoiceCheckQuery instance);
    partial void UpdateInvoiceCheckQuery(InvoiceCheckQuery instance);
    partial void DeleteInvoiceCheckQuery(InvoiceCheckQuery instance);
    partial void InsertHermesInvoice(HermesInvoice instance);
    partial void UpdateHermesInvoice(HermesInvoice instance);
    partial void DeleteHermesInvoice(HermesInvoice instance);
    #endregion
		
		public DBContextDataContext() : 
				base(global::TASK.Data.Properties.Settings.Default.eInvoiceConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DBContextDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBContextDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBContextDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBContextDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ResponseMessage> ResponseMessages
		{
			get
			{
				return this.GetTable<ResponseMessage>();
			}
		}
		
		public System.Data.Linq.Table<PrintConfig> PrintConfigs
		{
			get
			{
				return this.GetTable<PrintConfig>();
			}
		}
		
		public System.Data.Linq.Table<Print> Prints
		{
			get
			{
				return this.GetTable<Print>();
			}
		}
		
		public System.Data.Linq.Table<BasePdf> BasePdfs
		{
			get
			{
				return this.GetTable<BasePdf>();
			}
		}
		
		public System.Data.Linq.Table<HermesInvoiceDetail> HermesInvoiceDetails
		{
			get
			{
				return this.GetTable<HermesInvoiceDetail>();
			}
		}
		
		public System.Data.Linq.Table<InvoiceCancelCheck> InvoiceCancelChecks
		{
			get
			{
				return this.GetTable<InvoiceCancelCheck>();
			}
		}
		
		public System.Data.Linq.Table<HolidayConfig> HolidayConfigs
		{
			get
			{
				return this.GetTable<HolidayConfig>();
			}
		}
		
		public System.Data.Linq.Table<InvoiceCheckQuery> InvoiceCheckQueries
		{
			get
			{
				return this.GetTable<InvoiceCheckQuery>();
			}
		}
		
		public System.Data.Linq.Table<HermesInvoice> HermesInvoices
		{
			get
			{
				return this.GetTable<HermesInvoice>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ResponseMessage")]
	public partial class ResponseMessage : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _ReturnCodeField;
		
		private string _ErrorMessageField;
		
		private string _KeyField;
		
		private string _KHMSHDonField;
		
		private string _KHHDonField;
		
		private string _SHDonField;
		
		private string _MTCuuField;
		
		private string _PdfBase64Field;
		
		private string _ExceptionLogField;
		
		private System.Nullable<System.DateTime> _Created;
		
		private System.Nullable<System.DateTime> _TimeSent;
		
		private System.Nullable<System.DateTime> _TimeResponse;
		
		private System.Nullable<System.DateTime> _ExecuteTime;
		
		private string _ApiType;
		
		private string _TimeExecute;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnReturnCodeFieldChanging(string value);
    partial void OnReturnCodeFieldChanged();
    partial void OnErrorMessageFieldChanging(string value);
    partial void OnErrorMessageFieldChanged();
    partial void OnKeyFieldChanging(string value);
    partial void OnKeyFieldChanged();
    partial void OnKHMSHDonFieldChanging(string value);
    partial void OnKHMSHDonFieldChanged();
    partial void OnKHHDonFieldChanging(string value);
    partial void OnKHHDonFieldChanged();
    partial void OnSHDonFieldChanging(string value);
    partial void OnSHDonFieldChanged();
    partial void OnMTCuuFieldChanging(string value);
    partial void OnMTCuuFieldChanged();
    partial void OnPdfBase64FieldChanging(string value);
    partial void OnPdfBase64FieldChanged();
    partial void OnExceptionLogFieldChanging(string value);
    partial void OnExceptionLogFieldChanged();
    partial void OnCreatedChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedChanged();
    partial void OnTimeSentChanging(System.Nullable<System.DateTime> value);
    partial void OnTimeSentChanged();
    partial void OnTimeResponseChanging(System.Nullable<System.DateTime> value);
    partial void OnTimeResponseChanged();
    partial void OnExecuteTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnExecuteTimeChanged();
    partial void OnApiTypeChanging(string value);
    partial void OnApiTypeChanged();
    partial void OnTimeExecuteChanging(string value);
    partial void OnTimeExecuteChanged();
    #endregion
		
		public ResponseMessage()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReturnCodeField", DbType="VarChar(50)")]
		public string ReturnCodeField
		{
			get
			{
				return this._ReturnCodeField;
			}
			set
			{
				if ((this._ReturnCodeField != value))
				{
					this.OnReturnCodeFieldChanging(value);
					this.SendPropertyChanging();
					this._ReturnCodeField = value;
					this.SendPropertyChanged("ReturnCodeField");
					this.OnReturnCodeFieldChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ErrorMessageField", DbType="NVarChar(200)")]
		public string ErrorMessageField
		{
			get
			{
				return this._ErrorMessageField;
			}
			set
			{
				if ((this._ErrorMessageField != value))
				{
					this.OnErrorMessageFieldChanging(value);
					this.SendPropertyChanging();
					this._ErrorMessageField = value;
					this.SendPropertyChanged("ErrorMessageField");
					this.OnErrorMessageFieldChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KeyField", DbType="VarChar(50)")]
		public string KeyField
		{
			get
			{
				return this._KeyField;
			}
			set
			{
				if ((this._KeyField != value))
				{
					this.OnKeyFieldChanging(value);
					this.SendPropertyChanging();
					this._KeyField = value;
					this.SendPropertyChanged("KeyField");
					this.OnKeyFieldChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KHMSHDonField", DbType="VarChar(50)")]
		public string KHMSHDonField
		{
			get
			{
				return this._KHMSHDonField;
			}
			set
			{
				if ((this._KHMSHDonField != value))
				{
					this.OnKHMSHDonFieldChanging(value);
					this.SendPropertyChanging();
					this._KHMSHDonField = value;
					this.SendPropertyChanged("KHMSHDonField");
					this.OnKHMSHDonFieldChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KHHDonField", DbType="VarChar(50)")]
		public string KHHDonField
		{
			get
			{
				return this._KHHDonField;
			}
			set
			{
				if ((this._KHHDonField != value))
				{
					this.OnKHHDonFieldChanging(value);
					this.SendPropertyChanging();
					this._KHHDonField = value;
					this.SendPropertyChanged("KHHDonField");
					this.OnKHHDonFieldChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SHDonField", DbType="VarChar(50)")]
		public string SHDonField
		{
			get
			{
				return this._SHDonField;
			}
			set
			{
				if ((this._SHDonField != value))
				{
					this.OnSHDonFieldChanging(value);
					this.SendPropertyChanging();
					this._SHDonField = value;
					this.SendPropertyChanged("SHDonField");
					this.OnSHDonFieldChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MTCuuField", DbType="VarChar(50)")]
		public string MTCuuField
		{
			get
			{
				return this._MTCuuField;
			}
			set
			{
				if ((this._MTCuuField != value))
				{
					this.OnMTCuuFieldChanging(value);
					this.SendPropertyChanging();
					this._MTCuuField = value;
					this.SendPropertyChanged("MTCuuField");
					this.OnMTCuuFieldChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PdfBase64Field", DbType="NVarChar(MAX)")]
		public string PdfBase64Field
		{
			get
			{
				return this._PdfBase64Field;
			}
			set
			{
				if ((this._PdfBase64Field != value))
				{
					this.OnPdfBase64FieldChanging(value);
					this.SendPropertyChanging();
					this._PdfBase64Field = value;
					this.SendPropertyChanged("PdfBase64Field");
					this.OnPdfBase64FieldChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExceptionLogField", DbType="VarChar(MAX)")]
		public string ExceptionLogField
		{
			get
			{
				return this._ExceptionLogField;
			}
			set
			{
				if ((this._ExceptionLogField != value))
				{
					this.OnExceptionLogFieldChanging(value);
					this.SendPropertyChanging();
					this._ExceptionLogField = value;
					this.SendPropertyChanged("ExceptionLogField");
					this.OnExceptionLogFieldChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Created", DbType="DateTime")]
		public System.Nullable<System.DateTime> Created
		{
			get
			{
				return this._Created;
			}
			set
			{
				if ((this._Created != value))
				{
					this.OnCreatedChanging(value);
					this.SendPropertyChanging();
					this._Created = value;
					this.SendPropertyChanged("Created");
					this.OnCreatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeSent", DbType="DateTime")]
		public System.Nullable<System.DateTime> TimeSent
		{
			get
			{
				return this._TimeSent;
			}
			set
			{
				if ((this._TimeSent != value))
				{
					this.OnTimeSentChanging(value);
					this.SendPropertyChanging();
					this._TimeSent = value;
					this.SendPropertyChanged("TimeSent");
					this.OnTimeSentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeResponse", DbType="DateTime")]
		public System.Nullable<System.DateTime> TimeResponse
		{
			get
			{
				return this._TimeResponse;
			}
			set
			{
				if ((this._TimeResponse != value))
				{
					this.OnTimeResponseChanging(value);
					this.SendPropertyChanging();
					this._TimeResponse = value;
					this.SendPropertyChanged("TimeResponse");
					this.OnTimeResponseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExecuteTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> ExecuteTime
		{
			get
			{
				return this._ExecuteTime;
			}
			set
			{
				if ((this._ExecuteTime != value))
				{
					this.OnExecuteTimeChanging(value);
					this.SendPropertyChanging();
					this._ExecuteTime = value;
					this.SendPropertyChanged("ExecuteTime");
					this.OnExecuteTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApiType", DbType="VarChar(50)")]
		public string ApiType
		{
			get
			{
				return this._ApiType;
			}
			set
			{
				if ((this._ApiType != value))
				{
					this.OnApiTypeChanging(value);
					this.SendPropertyChanging();
					this._ApiType = value;
					this.SendPropertyChanged("ApiType");
					this.OnApiTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeExecute", DbType="VarChar(50)")]
		public string TimeExecute
		{
			get
			{
				return this._TimeExecute;
			}
			set
			{
				if ((this._TimeExecute != value))
				{
					this.OnTimeExecuteChanging(value);
					this.SendPropertyChanging();
					this._TimeExecute = value;
					this.SendPropertyChanged("TimeExecute");
					this.OnTimeExecuteChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PrintConfig")]
	public partial class PrintConfig : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _PrintUser;
		
		private string _Description;
		
		private string _PrintName;
		
		private string _PrinterNameReplace;
		
		private System.Nullable<int> _GroupName;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnPrintUserChanging(string value);
    partial void OnPrintUserChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnPrintNameChanging(string value);
    partial void OnPrintNameChanged();
    partial void OnPrinterNameReplaceChanging(string value);
    partial void OnPrinterNameReplaceChanged();
    partial void OnGroupNameChanging(System.Nullable<int> value);
    partial void OnGroupNameChanged();
    #endregion
		
		public PrintConfig()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrintUser", DbType="VarChar(500)")]
		public string PrintUser
		{
			get
			{
				return this._PrintUser;
			}
			set
			{
				if ((this._PrintUser != value))
				{
					this.OnPrintUserChanging(value);
					this.SendPropertyChanging();
					this._PrintUser = value;
					this.SendPropertyChanged("PrintUser");
					this.OnPrintUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(50)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrintName", DbType="VarChar(50)")]
		public string PrintName
		{
			get
			{
				return this._PrintName;
			}
			set
			{
				if ((this._PrintName != value))
				{
					this.OnPrintNameChanging(value);
					this.SendPropertyChanging();
					this._PrintName = value;
					this.SendPropertyChanged("PrintName");
					this.OnPrintNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrinterNameReplace", DbType="VarChar(50)")]
		public string PrinterNameReplace
		{
			get
			{
				return this._PrinterNameReplace;
			}
			set
			{
				if ((this._PrinterNameReplace != value))
				{
					this.OnPrinterNameReplaceChanging(value);
					this.SendPropertyChanging();
					this._PrinterNameReplace = value;
					this.SendPropertyChanged("PrinterNameReplace");
					this.OnPrinterNameReplaceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupName", DbType="Int")]
		public System.Nullable<int> GroupName
		{
			get
			{
				return this._GroupName;
			}
			set
			{
				if ((this._GroupName != value))
				{
					this.OnGroupNameChanging(value);
					this.SendPropertyChanging();
					this._GroupName = value;
					this.SendPropertyChanged("GroupName");
					this.OnGroupNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[Print]")]
	public partial class Print : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _PrintIns;
		
		private string _PrintType;
		
		private System.Nullable<int> _PrintRetry;
		
		private string _PrintUser;
		
		private System.Nullable<System.DateTime> _Created;
		
		private System.Nullable<int> _ThreadInstance;
		
		private System.Nullable<bool> _Status;
		
		private string _MessageLog;
		
		private string _PrintLink;
		
		private string _PrintShareLink;
		
		private System.Nullable<int> _GroupName;
		
		private System.Nullable<int> _Copy;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnPrintInsChanging(string value);
    partial void OnPrintInsChanged();
    partial void OnPrintTypeChanging(string value);
    partial void OnPrintTypeChanged();
    partial void OnPrintRetryChanging(System.Nullable<int> value);
    partial void OnPrintRetryChanged();
    partial void OnPrintUserChanging(string value);
    partial void OnPrintUserChanged();
    partial void OnCreatedChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedChanged();
    partial void OnThreadInstanceChanging(System.Nullable<int> value);
    partial void OnThreadInstanceChanged();
    partial void OnStatusChanging(System.Nullable<bool> value);
    partial void OnStatusChanged();
    partial void OnMessageLogChanging(string value);
    partial void OnMessageLogChanged();
    partial void OnPrintLinkChanging(string value);
    partial void OnPrintLinkChanged();
    partial void OnPrintShareLinkChanging(string value);
    partial void OnPrintShareLinkChanged();
    partial void OnGroupNameChanging(System.Nullable<int> value);
    partial void OnGroupNameChanged();
    partial void OnCopyChanging(System.Nullable<int> value);
    partial void OnCopyChanged();
    #endregion
		
		public Print()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrintIns", DbType="VarChar(50)")]
		public string PrintIns
		{
			get
			{
				return this._PrintIns;
			}
			set
			{
				if ((this._PrintIns != value))
				{
					this.OnPrintInsChanging(value);
					this.SendPropertyChanging();
					this._PrintIns = value;
					this.SendPropertyChanged("PrintIns");
					this.OnPrintInsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrintType", DbType="VarChar(50)")]
		public string PrintType
		{
			get
			{
				return this._PrintType;
			}
			set
			{
				if ((this._PrintType != value))
				{
					this.OnPrintTypeChanging(value);
					this.SendPropertyChanging();
					this._PrintType = value;
					this.SendPropertyChanged("PrintType");
					this.OnPrintTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrintRetry", DbType="Int")]
		public System.Nullable<int> PrintRetry
		{
			get
			{
				return this._PrintRetry;
			}
			set
			{
				if ((this._PrintRetry != value))
				{
					this.OnPrintRetryChanging(value);
					this.SendPropertyChanging();
					this._PrintRetry = value;
					this.SendPropertyChanged("PrintRetry");
					this.OnPrintRetryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrintUser", DbType="VarChar(500)")]
		public string PrintUser
		{
			get
			{
				return this._PrintUser;
			}
			set
			{
				if ((this._PrintUser != value))
				{
					this.OnPrintUserChanging(value);
					this.SendPropertyChanging();
					this._PrintUser = value;
					this.SendPropertyChanged("PrintUser");
					this.OnPrintUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Created", DbType="DateTime")]
		public System.Nullable<System.DateTime> Created
		{
			get
			{
				return this._Created;
			}
			set
			{
				if ((this._Created != value))
				{
					this.OnCreatedChanging(value);
					this.SendPropertyChanging();
					this._Created = value;
					this.SendPropertyChanged("Created");
					this.OnCreatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThreadInstance", DbType="Int")]
		public System.Nullable<int> ThreadInstance
		{
			get
			{
				return this._ThreadInstance;
			}
			set
			{
				if ((this._ThreadInstance != value))
				{
					this.OnThreadInstanceChanging(value);
					this.SendPropertyChanging();
					this._ThreadInstance = value;
					this.SendPropertyChanged("ThreadInstance");
					this.OnThreadInstanceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Bit")]
		public System.Nullable<bool> Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MessageLog", DbType="VarChar(200)")]
		public string MessageLog
		{
			get
			{
				return this._MessageLog;
			}
			set
			{
				if ((this._MessageLog != value))
				{
					this.OnMessageLogChanging(value);
					this.SendPropertyChanging();
					this._MessageLog = value;
					this.SendPropertyChanged("MessageLog");
					this.OnMessageLogChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrintLink", DbType="VarChar(200)")]
		public string PrintLink
		{
			get
			{
				return this._PrintLink;
			}
			set
			{
				if ((this._PrintLink != value))
				{
					this.OnPrintLinkChanging(value);
					this.SendPropertyChanging();
					this._PrintLink = value;
					this.SendPropertyChanged("PrintLink");
					this.OnPrintLinkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrintShareLink", DbType="VarChar(200)")]
		public string PrintShareLink
		{
			get
			{
				return this._PrintShareLink;
			}
			set
			{
				if ((this._PrintShareLink != value))
				{
					this.OnPrintShareLinkChanging(value);
					this.SendPropertyChanging();
					this._PrintShareLink = value;
					this.SendPropertyChanged("PrintShareLink");
					this.OnPrintShareLinkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupName", DbType="Int")]
		public System.Nullable<int> GroupName
		{
			get
			{
				return this._GroupName;
			}
			set
			{
				if ((this._GroupName != value))
				{
					this.OnGroupNameChanging(value);
					this.SendPropertyChanging();
					this._GroupName = value;
					this.SendPropertyChanged("GroupName");
					this.OnGroupNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Copy", DbType="Int")]
		public System.Nullable<int> Copy
		{
			get
			{
				return this._Copy;
			}
			set
			{
				if ((this._Copy != value))
				{
					this.OnCopyChanging(value);
					this.SendPropertyChanging();
					this._Copy = value;
					this.SendPropertyChanged("Copy");
					this.OnCopyChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BasePdf")]
	public partial class BasePdf : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _PDF;
		
		private string _InvoiceIns;
		
		private System.Nullable<System.DateTime> _Created;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnPDFChanging(string value);
    partial void OnPDFChanged();
    partial void OnInvoiceInsChanging(string value);
    partial void OnInvoiceInsChanged();
    partial void OnCreatedChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedChanged();
    #endregion
		
		public BasePdf()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PDF", DbType="VarChar(MAX)")]
		public string PDF
		{
			get
			{
				return this._PDF;
			}
			set
			{
				if ((this._PDF != value))
				{
					this.OnPDFChanging(value);
					this.SendPropertyChanging();
					this._PDF = value;
					this.SendPropertyChanged("PDF");
					this.OnPDFChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceIns", DbType="VarChar(50)")]
		public string InvoiceIns
		{
			get
			{
				return this._InvoiceIns;
			}
			set
			{
				if ((this._InvoiceIns != value))
				{
					this.OnInvoiceInsChanging(value);
					this.SendPropertyChanging();
					this._InvoiceIns = value;
					this.SendPropertyChanged("InvoiceIns");
					this.OnInvoiceInsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Created", DbType="DateTime")]
		public System.Nullable<System.DateTime> Created
		{
			get
			{
				return this._Created;
			}
			set
			{
				if ((this._Created != value))
				{
					this.OnCreatedChanging(value);
					this.SendPropertyChanging();
					this._Created = value;
					this.SendPropertyChanged("Created");
					this.OnCreatedChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HermesInvoiceDetail")]
	public partial class HermesInvoiceDetail : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _InvoiceIns;
		
		private string _InvoiceLineIns;
		
		private string _Item;
		
		private string _Unit;
		
		private System.Nullable<double> _Quantity;
		
		private System.Nullable<decimal> _UnitPrice;
		
		private System.Nullable<decimal> _Amount;
		
		private string _TaxRate;
		
		private System.Nullable<decimal> _VAT;
		
		private System.Nullable<bool> _MinCharged;
		
		private System.Nullable<System.Guid> _InvoiceDetailGuid;
		
		private System.Nullable<double> _StorageTimeLog;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnInvoiceInsChanging(string value);
    partial void OnInvoiceInsChanged();
    partial void OnInvoiceLineInsChanging(string value);
    partial void OnInvoiceLineInsChanged();
    partial void OnItemChanging(string value);
    partial void OnItemChanged();
    partial void OnUnitChanging(string value);
    partial void OnUnitChanged();
    partial void OnQuantityChanging(System.Nullable<double> value);
    partial void OnQuantityChanged();
    partial void OnUnitPriceChanging(System.Nullable<decimal> value);
    partial void OnUnitPriceChanged();
    partial void OnAmountChanging(System.Nullable<decimal> value);
    partial void OnAmountChanged();
    partial void OnTaxRateChanging(string value);
    partial void OnTaxRateChanged();
    partial void OnVATChanging(System.Nullable<decimal> value);
    partial void OnVATChanged();
    partial void OnMinChargedChanging(System.Nullable<bool> value);
    partial void OnMinChargedChanged();
    partial void OnInvoiceDetailGuidChanging(System.Nullable<System.Guid> value);
    partial void OnInvoiceDetailGuidChanged();
    partial void OnStorageTimeLogChanging(System.Nullable<double> value);
    partial void OnStorageTimeLogChanged();
    #endregion
		
		public HermesInvoiceDetail()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceIns", DbType="VarChar(50)")]
		public string InvoiceIns
		{
			get
			{
				return this._InvoiceIns;
			}
			set
			{
				if ((this._InvoiceIns != value))
				{
					this.OnInvoiceInsChanging(value);
					this.SendPropertyChanging();
					this._InvoiceIns = value;
					this.SendPropertyChanged("InvoiceIns");
					this.OnInvoiceInsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceLineIns", DbType="VarChar(50)")]
		public string InvoiceLineIns
		{
			get
			{
				return this._InvoiceLineIns;
			}
			set
			{
				if ((this._InvoiceLineIns != value))
				{
					this.OnInvoiceLineInsChanging(value);
					this.SendPropertyChanging();
					this._InvoiceLineIns = value;
					this.SendPropertyChanged("InvoiceLineIns");
					this.OnInvoiceLineInsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Item", DbType="NVarChar(200)")]
		public string Item
		{
			get
			{
				return this._Item;
			}
			set
			{
				if ((this._Item != value))
				{
					this.OnItemChanging(value);
					this.SendPropertyChanging();
					this._Item = value;
					this.SendPropertyChanged("Item");
					this.OnItemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Unit", DbType="VarChar(50)")]
		public string Unit
		{
			get
			{
				return this._Unit;
			}
			set
			{
				if ((this._Unit != value))
				{
					this.OnUnitChanging(value);
					this.SendPropertyChanging();
					this._Unit = value;
					this.SendPropertyChanged("Unit");
					this.OnUnitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quantity", DbType="Float")]
		public System.Nullable<double> Quantity
		{
			get
			{
				return this._Quantity;
			}
			set
			{
				if ((this._Quantity != value))
				{
					this.OnQuantityChanging(value);
					this.SendPropertyChanging();
					this._Quantity = value;
					this.SendPropertyChanged("Quantity");
					this.OnQuantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UnitPrice", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> UnitPrice
		{
			get
			{
				return this._UnitPrice;
			}
			set
			{
				if ((this._UnitPrice != value))
				{
					this.OnUnitPriceChanging(value);
					this.SendPropertyChanging();
					this._UnitPrice = value;
					this.SendPropertyChanged("UnitPrice");
					this.OnUnitPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Amount", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Amount
		{
			get
			{
				return this._Amount;
			}
			set
			{
				if ((this._Amount != value))
				{
					this.OnAmountChanging(value);
					this.SendPropertyChanging();
					this._Amount = value;
					this.SendPropertyChanged("Amount");
					this.OnAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaxRate", DbType="VarChar(50)")]
		public string TaxRate
		{
			get
			{
				return this._TaxRate;
			}
			set
			{
				if ((this._TaxRate != value))
				{
					this.OnTaxRateChanging(value);
					this.SendPropertyChanging();
					this._TaxRate = value;
					this.SendPropertyChanged("TaxRate");
					this.OnTaxRateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VAT", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> VAT
		{
			get
			{
				return this._VAT;
			}
			set
			{
				if ((this._VAT != value))
				{
					this.OnVATChanging(value);
					this.SendPropertyChanging();
					this._VAT = value;
					this.SendPropertyChanged("VAT");
					this.OnVATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MinCharged", DbType="Bit")]
		public System.Nullable<bool> MinCharged
		{
			get
			{
				return this._MinCharged;
			}
			set
			{
				if ((this._MinCharged != value))
				{
					this.OnMinChargedChanging(value);
					this.SendPropertyChanging();
					this._MinCharged = value;
					this.SendPropertyChanged("MinCharged");
					this.OnMinChargedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceDetailGuid", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> InvoiceDetailGuid
		{
			get
			{
				return this._InvoiceDetailGuid;
			}
			set
			{
				if ((this._InvoiceDetailGuid != value))
				{
					this.OnInvoiceDetailGuidChanging(value);
					this.SendPropertyChanging();
					this._InvoiceDetailGuid = value;
					this.SendPropertyChanged("InvoiceDetailGuid");
					this.OnInvoiceDetailGuidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StorageTimeLog", DbType="Float")]
		public System.Nullable<double> StorageTimeLog
		{
			get
			{
				return this._StorageTimeLog;
			}
			set
			{
				if ((this._StorageTimeLog != value))
				{
					this.OnStorageTimeLogChanging(value);
					this.SendPropertyChanging();
					this._StorageTimeLog = value;
					this.SendPropertyChanged("StorageTimeLog");
					this.OnStorageTimeLogChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.InvoiceCancelCheck")]
	public partial class InvoiceCancelCheck : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _InvoiceIsn;
		
		private System.Nullable<System.DateTime> _Created;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnInvoiceIsnChanging(string value);
    partial void OnInvoiceIsnChanged();
    partial void OnCreatedChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedChanged();
    #endregion
		
		public InvoiceCancelCheck()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceIsn", DbType="VarChar(50)")]
		public string InvoiceIsn
		{
			get
			{
				return this._InvoiceIsn;
			}
			set
			{
				if ((this._InvoiceIsn != value))
				{
					this.OnInvoiceIsnChanging(value);
					this.SendPropertyChanging();
					this._InvoiceIsn = value;
					this.SendPropertyChanged("InvoiceIsn");
					this.OnInvoiceIsnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Created", DbType="DateTime")]
		public System.Nullable<System.DateTime> Created
		{
			get
			{
				return this._Created;
			}
			set
			{
				if ((this._Created != value))
				{
					this.OnCreatedChanging(value);
					this.SendPropertyChanging();
					this._Created = value;
					this.SendPropertyChanged("Created");
					this.OnCreatedChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HolidayConfig")]
	public partial class HolidayConfig : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<System.DateTime> _DateHoliday;
		
		private System.Nullable<System.DateTime> _Created;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnDateHolidayChanging(System.Nullable<System.DateTime> value);
    partial void OnDateHolidayChanged();
    partial void OnCreatedChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedChanged();
    #endregion
		
		public HolidayConfig()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateHoliday", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateHoliday
		{
			get
			{
				return this._DateHoliday;
			}
			set
			{
				if ((this._DateHoliday != value))
				{
					this.OnDateHolidayChanging(value);
					this.SendPropertyChanging();
					this._DateHoliday = value;
					this.SendPropertyChanged("DateHoliday");
					this.OnDateHolidayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Created", DbType="DateTime")]
		public System.Nullable<System.DateTime> Created
		{
			get
			{
				return this._Created;
			}
			set
			{
				if ((this._Created != value))
				{
					this.OnCreatedChanging(value);
					this.SendPropertyChanging();
					this._Created = value;
					this.SendPropertyChanged("Created");
					this.OnCreatedChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.InvoiceCheckQuery")]
	public partial class InvoiceCheckQuery : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _InvoiceIsn;
		
		private System.Nullable<System.DateTime> _Created;
		
		private System.Nullable<bool> _Status;
		
		private System.Nullable<int> _Retry;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnInvoiceIsnChanging(string value);
    partial void OnInvoiceIsnChanged();
    partial void OnCreatedChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedChanged();
    partial void OnStatusChanging(System.Nullable<bool> value);
    partial void OnStatusChanged();
    partial void OnRetryChanging(System.Nullable<int> value);
    partial void OnRetryChanged();
    #endregion
		
		public InvoiceCheckQuery()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceIsn", DbType="VarChar(50)")]
		public string InvoiceIsn
		{
			get
			{
				return this._InvoiceIsn;
			}
			set
			{
				if ((this._InvoiceIsn != value))
				{
					this.OnInvoiceIsnChanging(value);
					this.SendPropertyChanging();
					this._InvoiceIsn = value;
					this.SendPropertyChanged("InvoiceIsn");
					this.OnInvoiceIsnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Created", DbType="DateTime")]
		public System.Nullable<System.DateTime> Created
		{
			get
			{
				return this._Created;
			}
			set
			{
				if ((this._Created != value))
				{
					this.OnCreatedChanging(value);
					this.SendPropertyChanging();
					this._Created = value;
					this.SendPropertyChanged("Created");
					this.OnCreatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Bit")]
		public System.Nullable<bool> Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Retry", DbType="Int")]
		public System.Nullable<int> Retry
		{
			get
			{
				return this._Retry;
			}
			set
			{
				if ((this._Retry != value))
				{
					this.OnRetryChanging(value);
					this.SendPropertyChanging();
					this._Retry = value;
					this.SendPropertyChanged("Retry");
					this.OnRetryChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HermesInvoice")]
	public partial class HermesInvoice : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _InvoiceIsn;
		
		private string _InvoiceRunIsn;
		
		private string _Payment;
		
		private string _InvoiceNumber;
		
		private string _InvoiceType;
		
		private System.Nullable<System.DateTime> _InvoiceDate;
		
		private System.Nullable<decimal> _InvoiceTotalAmount;
		
		private System.Nullable<decimal> _InvoiceTotalVatAmount;
		
		private string _AWB_Prefix;
		
		private string _AWB_Serial;
		
		private string _Hawb;
		
		private System.Nullable<System.DateTime> _InvoiceDatime;
		
		private string _KundName;
		
		private string _PersonName;
		
		private string _Address;
		
		private string _TaxCode;
		
		private System.Nullable<bool> _Status;
		
		private System.Nullable<int> _Retry;
		
		private string _ObjectType;
		
		private string _InvoiceLink;
		
		private System.Nullable<System.DateTime> _TimeSent;
		
		private System.Nullable<System.DateTime> _TimeReponse;
		
		private string _ExecuteTime;
		
		private string _EInvoiceLink;
		
		private System.Nullable<System.DateTime> _Created;
		
		private System.Nullable<int> _Sequence;
		
		private System.Nullable<decimal> _InvoiceTotalNoVatAmount;
		
		private string _AWB;
		
		private string _PrinterNetworkName;
		
		private System.Nullable<System.Guid> _InvoiceGuid;
		
		private string _ReferenceNo;
		
		private System.Nullable<int> _InvoiceStatus;
		
		private string _InvoiceDescription;
		
		private string _Email;
		
		private string _Phone;
		
		private string _Note;
		
		private System.Nullable<bool> _IsCancel;
		
		private System.Nullable<System.DateTime> _CancelDateTime;
		
		private System.Nullable<int> _ExceptionStatus;
		
		private string _CancelReason;
		
		private string _EInvoiceSearchLink;
		
		private string _SearchCode;
		
		private System.Nullable<bool> _ReExportInvoice;
		
		private System.Nullable<bool> _InvoiceCheckAddtional;
		
		private string _PaymentDescription;
		
		private string _InvoiceFieldType;
		
		private string _InvoiceFieldForm;
		
		private string _InvoiceFieldSerial;
		
		private string _Idt;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnInvoiceIsnChanging(string value);
    partial void OnInvoiceIsnChanged();
    partial void OnInvoiceRunIsnChanging(string value);
    partial void OnInvoiceRunIsnChanged();
    partial void OnPaymentChanging(string value);
    partial void OnPaymentChanged();
    partial void OnInvoiceNumberChanging(string value);
    partial void OnInvoiceNumberChanged();
    partial void OnInvoiceTypeChanging(string value);
    partial void OnInvoiceTypeChanged();
    partial void OnInvoiceDateChanging(System.Nullable<System.DateTime> value);
    partial void OnInvoiceDateChanged();
    partial void OnInvoiceTotalAmountChanging(System.Nullable<decimal> value);
    partial void OnInvoiceTotalAmountChanged();
    partial void OnInvoiceTotalVatAmountChanging(System.Nullable<decimal> value);
    partial void OnInvoiceTotalVatAmountChanged();
    partial void OnAWB_PrefixChanging(string value);
    partial void OnAWB_PrefixChanged();
    partial void OnAWB_SerialChanging(string value);
    partial void OnAWB_SerialChanged();
    partial void OnHawbChanging(string value);
    partial void OnHawbChanged();
    partial void OnInvoiceDatimeChanging(System.Nullable<System.DateTime> value);
    partial void OnInvoiceDatimeChanged();
    partial void OnKundNameChanging(string value);
    partial void OnKundNameChanged();
    partial void OnPersonNameChanging(string value);
    partial void OnPersonNameChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnTaxCodeChanging(string value);
    partial void OnTaxCodeChanged();
    partial void OnStatusChanging(System.Nullable<bool> value);
    partial void OnStatusChanged();
    partial void OnRetryChanging(System.Nullable<int> value);
    partial void OnRetryChanged();
    partial void OnObjectTypeChanging(string value);
    partial void OnObjectTypeChanged();
    partial void OnInvoiceLinkChanging(string value);
    partial void OnInvoiceLinkChanged();
    partial void OnTimeSentChanging(System.Nullable<System.DateTime> value);
    partial void OnTimeSentChanged();
    partial void OnTimeReponseChanging(System.Nullable<System.DateTime> value);
    partial void OnTimeReponseChanged();
    partial void OnExecuteTimeChanging(string value);
    partial void OnExecuteTimeChanged();
    partial void OnEInvoiceLinkChanging(string value);
    partial void OnEInvoiceLinkChanged();
    partial void OnCreatedChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedChanged();
    partial void OnSequenceChanging(System.Nullable<int> value);
    partial void OnSequenceChanged();
    partial void OnInvoiceTotalNoVatAmountChanging(System.Nullable<decimal> value);
    partial void OnInvoiceTotalNoVatAmountChanged();
    partial void OnAWBChanging(string value);
    partial void OnAWBChanged();
    partial void OnPrinterNetworkNameChanging(string value);
    partial void OnPrinterNetworkNameChanged();
    partial void OnInvoiceGuidChanging(System.Nullable<System.Guid> value);
    partial void OnInvoiceGuidChanged();
    partial void OnReferenceNoChanging(string value);
    partial void OnReferenceNoChanged();
    partial void OnInvoiceStatusChanging(System.Nullable<int> value);
    partial void OnInvoiceStatusChanged();
    partial void OnInvoiceDescriptionChanging(string value);
    partial void OnInvoiceDescriptionChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnPhoneChanging(string value);
    partial void OnPhoneChanged();
    partial void OnNoteChanging(string value);
    partial void OnNoteChanged();
    partial void OnIsCancelChanging(System.Nullable<bool> value);
    partial void OnIsCancelChanged();
    partial void OnCancelDateTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnCancelDateTimeChanged();
    partial void OnExceptionStatusChanging(System.Nullable<int> value);
    partial void OnExceptionStatusChanged();
    partial void OnCancelReasonChanging(string value);
    partial void OnCancelReasonChanged();
    partial void OnEInvoiceSearchLinkChanging(string value);
    partial void OnEInvoiceSearchLinkChanged();
    partial void OnSearchCodeChanging(string value);
    partial void OnSearchCodeChanged();
    partial void OnReExportInvoiceChanging(System.Nullable<bool> value);
    partial void OnReExportInvoiceChanged();
    partial void OnInvoiceCheckAddtionalChanging(System.Nullable<bool> value);
    partial void OnInvoiceCheckAddtionalChanged();
    partial void OnPaymentDescriptionChanging(string value);
    partial void OnPaymentDescriptionChanged();
    partial void OnInvoiceFieldTypeChanging(string value);
    partial void OnInvoiceFieldTypeChanged();
    partial void OnInvoiceFieldFormChanging(string value);
    partial void OnInvoiceFieldFormChanged();
    partial void OnInvoiceFieldSerialChanging(string value);
    partial void OnInvoiceFieldSerialChanged();
    partial void OnIdtChanging(string value);
    partial void OnIdtChanged();
    #endregion
		
		public HermesInvoice()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceIsn", DbType="VarChar(50)")]
		public string InvoiceIsn
		{
			get
			{
				return this._InvoiceIsn;
			}
			set
			{
				if ((this._InvoiceIsn != value))
				{
					this.OnInvoiceIsnChanging(value);
					this.SendPropertyChanging();
					this._InvoiceIsn = value;
					this.SendPropertyChanged("InvoiceIsn");
					this.OnInvoiceIsnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceRunIsn", DbType="VarChar(50)")]
		public string InvoiceRunIsn
		{
			get
			{
				return this._InvoiceRunIsn;
			}
			set
			{
				if ((this._InvoiceRunIsn != value))
				{
					this.OnInvoiceRunIsnChanging(value);
					this.SendPropertyChanging();
					this._InvoiceRunIsn = value;
					this.SendPropertyChanged("InvoiceRunIsn");
					this.OnInvoiceRunIsnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Payment", DbType="VarChar(50)")]
		public string Payment
		{
			get
			{
				return this._Payment;
			}
			set
			{
				if ((this._Payment != value))
				{
					this.OnPaymentChanging(value);
					this.SendPropertyChanging();
					this._Payment = value;
					this.SendPropertyChanged("Payment");
					this.OnPaymentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceNumber", DbType="VarChar(50)")]
		public string InvoiceNumber
		{
			get
			{
				return this._InvoiceNumber;
			}
			set
			{
				if ((this._InvoiceNumber != value))
				{
					this.OnInvoiceNumberChanging(value);
					this.SendPropertyChanging();
					this._InvoiceNumber = value;
					this.SendPropertyChanged("InvoiceNumber");
					this.OnInvoiceNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceType", DbType="VarChar(50)")]
		public string InvoiceType
		{
			get
			{
				return this._InvoiceType;
			}
			set
			{
				if ((this._InvoiceType != value))
				{
					this.OnInvoiceTypeChanging(value);
					this.SendPropertyChanging();
					this._InvoiceType = value;
					this.SendPropertyChanged("InvoiceType");
					this.OnInvoiceTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceDate", DbType="Date")]
		public System.Nullable<System.DateTime> InvoiceDate
		{
			get
			{
				return this._InvoiceDate;
			}
			set
			{
				if ((this._InvoiceDate != value))
				{
					this.OnInvoiceDateChanging(value);
					this.SendPropertyChanging();
					this._InvoiceDate = value;
					this.SendPropertyChanged("InvoiceDate");
					this.OnInvoiceDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceTotalAmount", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> InvoiceTotalAmount
		{
			get
			{
				return this._InvoiceTotalAmount;
			}
			set
			{
				if ((this._InvoiceTotalAmount != value))
				{
					this.OnInvoiceTotalAmountChanging(value);
					this.SendPropertyChanging();
					this._InvoiceTotalAmount = value;
					this.SendPropertyChanged("InvoiceTotalAmount");
					this.OnInvoiceTotalAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceTotalVatAmount", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> InvoiceTotalVatAmount
		{
			get
			{
				return this._InvoiceTotalVatAmount;
			}
			set
			{
				if ((this._InvoiceTotalVatAmount != value))
				{
					this.OnInvoiceTotalVatAmountChanging(value);
					this.SendPropertyChanging();
					this._InvoiceTotalVatAmount = value;
					this.SendPropertyChanged("InvoiceTotalVatAmount");
					this.OnInvoiceTotalVatAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AWB_Prefix", DbType="VarChar(50)")]
		public string AWB_Prefix
		{
			get
			{
				return this._AWB_Prefix;
			}
			set
			{
				if ((this._AWB_Prefix != value))
				{
					this.OnAWB_PrefixChanging(value);
					this.SendPropertyChanging();
					this._AWB_Prefix = value;
					this.SendPropertyChanged("AWB_Prefix");
					this.OnAWB_PrefixChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AWB_Serial", DbType="VarChar(50)")]
		public string AWB_Serial
		{
			get
			{
				return this._AWB_Serial;
			}
			set
			{
				if ((this._AWB_Serial != value))
				{
					this.OnAWB_SerialChanging(value);
					this.SendPropertyChanging();
					this._AWB_Serial = value;
					this.SendPropertyChanged("AWB_Serial");
					this.OnAWB_SerialChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hawb", DbType="VarChar(50)")]
		public string Hawb
		{
			get
			{
				return this._Hawb;
			}
			set
			{
				if ((this._Hawb != value))
				{
					this.OnHawbChanging(value);
					this.SendPropertyChanging();
					this._Hawb = value;
					this.SendPropertyChanged("Hawb");
					this.OnHawbChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceDatime", DbType="DateTime")]
		public System.Nullable<System.DateTime> InvoiceDatime
		{
			get
			{
				return this._InvoiceDatime;
			}
			set
			{
				if ((this._InvoiceDatime != value))
				{
					this.OnInvoiceDatimeChanging(value);
					this.SendPropertyChanging();
					this._InvoiceDatime = value;
					this.SendPropertyChanged("InvoiceDatime");
					this.OnInvoiceDatimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KundName", DbType="NVarChar(500)")]
		public string KundName
		{
			get
			{
				return this._KundName;
			}
			set
			{
				if ((this._KundName != value))
				{
					this.OnKundNameChanging(value);
					this.SendPropertyChanging();
					this._KundName = value;
					this.SendPropertyChanged("KundName");
					this.OnKundNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PersonName", DbType="NVarChar(100)")]
		public string PersonName
		{
			get
			{
				return this._PersonName;
			}
			set
			{
				if ((this._PersonName != value))
				{
					this.OnPersonNameChanging(value);
					this.SendPropertyChanging();
					this._PersonName = value;
					this.SendPropertyChanged("PersonName");
					this.OnPersonNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="NVarChar(500)")]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this.OnAddressChanging(value);
					this.SendPropertyChanging();
					this._Address = value;
					this.SendPropertyChanged("Address");
					this.OnAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaxCode", DbType="VarChar(50)")]
		public string TaxCode
		{
			get
			{
				return this._TaxCode;
			}
			set
			{
				if ((this._TaxCode != value))
				{
					this.OnTaxCodeChanging(value);
					this.SendPropertyChanging();
					this._TaxCode = value;
					this.SendPropertyChanged("TaxCode");
					this.OnTaxCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Bit")]
		public System.Nullable<bool> Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Retry", DbType="Int")]
		public System.Nullable<int> Retry
		{
			get
			{
				return this._Retry;
			}
			set
			{
				if ((this._Retry != value))
				{
					this.OnRetryChanging(value);
					this.SendPropertyChanging();
					this._Retry = value;
					this.SendPropertyChanged("Retry");
					this.OnRetryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ObjectType", DbType="VarChar(50)")]
		public string ObjectType
		{
			get
			{
				return this._ObjectType;
			}
			set
			{
				if ((this._ObjectType != value))
				{
					this.OnObjectTypeChanging(value);
					this.SendPropertyChanging();
					this._ObjectType = value;
					this.SendPropertyChanged("ObjectType");
					this.OnObjectTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceLink", DbType="NVarChar(500)")]
		public string InvoiceLink
		{
			get
			{
				return this._InvoiceLink;
			}
			set
			{
				if ((this._InvoiceLink != value))
				{
					this.OnInvoiceLinkChanging(value);
					this.SendPropertyChanging();
					this._InvoiceLink = value;
					this.SendPropertyChanged("InvoiceLink");
					this.OnInvoiceLinkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeSent", DbType="DateTime")]
		public System.Nullable<System.DateTime> TimeSent
		{
			get
			{
				return this._TimeSent;
			}
			set
			{
				if ((this._TimeSent != value))
				{
					this.OnTimeSentChanging(value);
					this.SendPropertyChanging();
					this._TimeSent = value;
					this.SendPropertyChanged("TimeSent");
					this.OnTimeSentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeReponse", DbType="DateTime")]
		public System.Nullable<System.DateTime> TimeReponse
		{
			get
			{
				return this._TimeReponse;
			}
			set
			{
				if ((this._TimeReponse != value))
				{
					this.OnTimeReponseChanging(value);
					this.SendPropertyChanging();
					this._TimeReponse = value;
					this.SendPropertyChanged("TimeReponse");
					this.OnTimeReponseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExecuteTime", DbType="NVarChar(50)")]
		public string ExecuteTime
		{
			get
			{
				return this._ExecuteTime;
			}
			set
			{
				if ((this._ExecuteTime != value))
				{
					this.OnExecuteTimeChanging(value);
					this.SendPropertyChanging();
					this._ExecuteTime = value;
					this.SendPropertyChanged("ExecuteTime");
					this.OnExecuteTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EInvoiceLink", DbType="NVarChar(200)")]
		public string EInvoiceLink
		{
			get
			{
				return this._EInvoiceLink;
			}
			set
			{
				if ((this._EInvoiceLink != value))
				{
					this.OnEInvoiceLinkChanging(value);
					this.SendPropertyChanging();
					this._EInvoiceLink = value;
					this.SendPropertyChanged("EInvoiceLink");
					this.OnEInvoiceLinkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Created", DbType="DateTime")]
		public System.Nullable<System.DateTime> Created
		{
			get
			{
				return this._Created;
			}
			set
			{
				if ((this._Created != value))
				{
					this.OnCreatedChanging(value);
					this.SendPropertyChanging();
					this._Created = value;
					this.SendPropertyChanged("Created");
					this.OnCreatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sequence", DbType="Int")]
		public System.Nullable<int> Sequence
		{
			get
			{
				return this._Sequence;
			}
			set
			{
				if ((this._Sequence != value))
				{
					this.OnSequenceChanging(value);
					this.SendPropertyChanging();
					this._Sequence = value;
					this.SendPropertyChanged("Sequence");
					this.OnSequenceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceTotalNoVatAmount", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> InvoiceTotalNoVatAmount
		{
			get
			{
				return this._InvoiceTotalNoVatAmount;
			}
			set
			{
				if ((this._InvoiceTotalNoVatAmount != value))
				{
					this.OnInvoiceTotalNoVatAmountChanging(value);
					this.SendPropertyChanging();
					this._InvoiceTotalNoVatAmount = value;
					this.SendPropertyChanged("InvoiceTotalNoVatAmount");
					this.OnInvoiceTotalNoVatAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AWB", DbType="VarChar(50)")]
		public string AWB
		{
			get
			{
				return this._AWB;
			}
			set
			{
				if ((this._AWB != value))
				{
					this.OnAWBChanging(value);
					this.SendPropertyChanging();
					this._AWB = value;
					this.SendPropertyChanged("AWB");
					this.OnAWBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrinterNetworkName", DbType="NVarChar(100)")]
		public string PrinterNetworkName
		{
			get
			{
				return this._PrinterNetworkName;
			}
			set
			{
				if ((this._PrinterNetworkName != value))
				{
					this.OnPrinterNetworkNameChanging(value);
					this.SendPropertyChanging();
					this._PrinterNetworkName = value;
					this.SendPropertyChanged("PrinterNetworkName");
					this.OnPrinterNetworkNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceGuid", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> InvoiceGuid
		{
			get
			{
				return this._InvoiceGuid;
			}
			set
			{
				if ((this._InvoiceGuid != value))
				{
					this.OnInvoiceGuidChanging(value);
					this.SendPropertyChanging();
					this._InvoiceGuid = value;
					this.SendPropertyChanged("InvoiceGuid");
					this.OnInvoiceGuidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReferenceNo", DbType="VarChar(50)")]
		public string ReferenceNo
		{
			get
			{
				return this._ReferenceNo;
			}
			set
			{
				if ((this._ReferenceNo != value))
				{
					this.OnReferenceNoChanging(value);
					this.SendPropertyChanging();
					this._ReferenceNo = value;
					this.SendPropertyChanged("ReferenceNo");
					this.OnReferenceNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceStatus", DbType="Int")]
		public System.Nullable<int> InvoiceStatus
		{
			get
			{
				return this._InvoiceStatus;
			}
			set
			{
				if ((this._InvoiceStatus != value))
				{
					this.OnInvoiceStatusChanging(value);
					this.SendPropertyChanging();
					this._InvoiceStatus = value;
					this.SendPropertyChanged("InvoiceStatus");
					this.OnInvoiceStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceDescription", DbType="NVarChar(50)")]
		public string InvoiceDescription
		{
			get
			{
				return this._InvoiceDescription;
			}
			set
			{
				if ((this._InvoiceDescription != value))
				{
					this.OnInvoiceDescriptionChanging(value);
					this.SendPropertyChanging();
					this._InvoiceDescription = value;
					this.SendPropertyChanged("InvoiceDescription");
					this.OnInvoiceDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(500)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="VarChar(20)")]
		public string Phone
		{
			get
			{
				return this._Phone;
			}
			set
			{
				if ((this._Phone != value))
				{
					this.OnPhoneChanging(value);
					this.SendPropertyChanging();
					this._Phone = value;
					this.SendPropertyChanged("Phone");
					this.OnPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Note", DbType="NVarChar(100)")]
		public string Note
		{
			get
			{
				return this._Note;
			}
			set
			{
				if ((this._Note != value))
				{
					this.OnNoteChanging(value);
					this.SendPropertyChanging();
					this._Note = value;
					this.SendPropertyChanged("Note");
					this.OnNoteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsCancel", DbType="Bit")]
		public System.Nullable<bool> IsCancel
		{
			get
			{
				return this._IsCancel;
			}
			set
			{
				if ((this._IsCancel != value))
				{
					this.OnIsCancelChanging(value);
					this.SendPropertyChanging();
					this._IsCancel = value;
					this.SendPropertyChanged("IsCancel");
					this.OnIsCancelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CancelDateTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> CancelDateTime
		{
			get
			{
				return this._CancelDateTime;
			}
			set
			{
				if ((this._CancelDateTime != value))
				{
					this.OnCancelDateTimeChanging(value);
					this.SendPropertyChanging();
					this._CancelDateTime = value;
					this.SendPropertyChanged("CancelDateTime");
					this.OnCancelDateTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExceptionStatus", DbType="Int")]
		public System.Nullable<int> ExceptionStatus
		{
			get
			{
				return this._ExceptionStatus;
			}
			set
			{
				if ((this._ExceptionStatus != value))
				{
					this.OnExceptionStatusChanging(value);
					this.SendPropertyChanging();
					this._ExceptionStatus = value;
					this.SendPropertyChanged("ExceptionStatus");
					this.OnExceptionStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CancelReason", DbType="NVarChar(100)")]
		public string CancelReason
		{
			get
			{
				return this._CancelReason;
			}
			set
			{
				if ((this._CancelReason != value))
				{
					this.OnCancelReasonChanging(value);
					this.SendPropertyChanging();
					this._CancelReason = value;
					this.SendPropertyChanged("CancelReason");
					this.OnCancelReasonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EInvoiceSearchLink", DbType="VarChar(200)")]
		public string EInvoiceSearchLink
		{
			get
			{
				return this._EInvoiceSearchLink;
			}
			set
			{
				if ((this._EInvoiceSearchLink != value))
				{
					this.OnEInvoiceSearchLinkChanging(value);
					this.SendPropertyChanging();
					this._EInvoiceSearchLink = value;
					this.SendPropertyChanged("EInvoiceSearchLink");
					this.OnEInvoiceSearchLinkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SearchCode", DbType="VarChar(50)")]
		public string SearchCode
		{
			get
			{
				return this._SearchCode;
			}
			set
			{
				if ((this._SearchCode != value))
				{
					this.OnSearchCodeChanging(value);
					this.SendPropertyChanging();
					this._SearchCode = value;
					this.SendPropertyChanged("SearchCode");
					this.OnSearchCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReExportInvoice", DbType="Bit")]
		public System.Nullable<bool> ReExportInvoice
		{
			get
			{
				return this._ReExportInvoice;
			}
			set
			{
				if ((this._ReExportInvoice != value))
				{
					this.OnReExportInvoiceChanging(value);
					this.SendPropertyChanging();
					this._ReExportInvoice = value;
					this.SendPropertyChanged("ReExportInvoice");
					this.OnReExportInvoiceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceCheckAddtional", DbType="Bit")]
		public System.Nullable<bool> InvoiceCheckAddtional
		{
			get
			{
				return this._InvoiceCheckAddtional;
			}
			set
			{
				if ((this._InvoiceCheckAddtional != value))
				{
					this.OnInvoiceCheckAddtionalChanging(value);
					this.SendPropertyChanging();
					this._InvoiceCheckAddtional = value;
					this.SendPropertyChanged("InvoiceCheckAddtional");
					this.OnInvoiceCheckAddtionalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaymentDescription", DbType="VarChar(50)")]
		public string PaymentDescription
		{
			get
			{
				return this._PaymentDescription;
			}
			set
			{
				if ((this._PaymentDescription != value))
				{
					this.OnPaymentDescriptionChanging(value);
					this.SendPropertyChanging();
					this._PaymentDescription = value;
					this.SendPropertyChanged("PaymentDescription");
					this.OnPaymentDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceFieldType", DbType="NVarChar(50)")]
		public string InvoiceFieldType
		{
			get
			{
				return this._InvoiceFieldType;
			}
			set
			{
				if ((this._InvoiceFieldType != value))
				{
					this.OnInvoiceFieldTypeChanging(value);
					this.SendPropertyChanging();
					this._InvoiceFieldType = value;
					this.SendPropertyChanged("InvoiceFieldType");
					this.OnInvoiceFieldTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceFieldForm", DbType="NVarChar(50)")]
		public string InvoiceFieldForm
		{
			get
			{
				return this._InvoiceFieldForm;
			}
			set
			{
				if ((this._InvoiceFieldForm != value))
				{
					this.OnInvoiceFieldFormChanging(value);
					this.SendPropertyChanging();
					this._InvoiceFieldForm = value;
					this.SendPropertyChanged("InvoiceFieldForm");
					this.OnInvoiceFieldFormChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceFieldSerial", DbType="NVarChar(50)")]
		public string InvoiceFieldSerial
		{
			get
			{
				return this._InvoiceFieldSerial;
			}
			set
			{
				if ((this._InvoiceFieldSerial != value))
				{
					this.OnInvoiceFieldSerialChanging(value);
					this.SendPropertyChanging();
					this._InvoiceFieldSerial = value;
					this.SendPropertyChanged("InvoiceFieldSerial");
					this.OnInvoiceFieldSerialChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Idt", DbType="VarChar(50)")]
		public string Idt
		{
			get
			{
				return this._Idt;
			}
			set
			{
				if ((this._Idt != value))
				{
					this.OnIdtChanging(value);
					this.SendPropertyChanging();
					this._Idt = value;
					this.SendPropertyChanged("Idt");
					this.OnIdtChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
