//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace TASK.Service.vn.cinvoice.api {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ALSServiceSoap", Namespace="http://microsoft.com/webservices/")]
    public partial class ALSService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ApiPHanhHDonOperationCompleted;
        
        private System.Threading.SendOrPostCallback ApiPHanhHDonKSoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ApiHuyHDonOperationCompleted;
        
        private System.Threading.SendOrPostCallback ApiKyHDonOperationCompleted;
        
        private System.Threading.SendOrPostCallback ApiInHoadonOperationCompleted;
        
        private System.Threading.SendOrPostCallback ApiLayCTietHDonOperationCompleted;
        
        private System.Threading.SendOrPostCallback ApiLayTTinMSKHHDonOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ALSService() {
            this.Url = global::TASK.Service.Properties.Settings.Default.TASK_Service_vn_cinvoice_api_ALSService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ApiPHanhHDonCompletedEventHandler ApiPHanhHDonCompleted;
        
        /// <remarks/>
        public event ApiPHanhHDonKSoCompletedEventHandler ApiPHanhHDonKSoCompleted;
        
        /// <remarks/>
        public event ApiHuyHDonCompletedEventHandler ApiHuyHDonCompleted;
        
        /// <remarks/>
        public event ApiKyHDonCompletedEventHandler ApiKyHDonCompleted;
        
        /// <remarks/>
        public event ApiInHoadonCompletedEventHandler ApiInHoadonCompleted;
        
        /// <remarks/>
        public event ApiLayCTietHDonCompletedEventHandler ApiLayCTietHDonCompleted;
        
        /// <remarks/>
        public event ApiLayTTinMSKHHDonCompletedEventHandler ApiLayTTinMSKHHDonCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://microsoft.com/webservices/ApiPHanhHDon", RequestNamespace="http://microsoft.com/webservices/", ResponseNamespace="http://microsoft.com/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ApiPHanhHDon(string b_nsd, string b_mk, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] HDon HDon) {
            object[] results = this.Invoke("ApiPHanhHDon", new object[] {
                        b_nsd,
                        b_mk,
                        HDon});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ApiPHanhHDonAsync(string b_nsd, string b_mk, HDon HDon) {
            this.ApiPHanhHDonAsync(b_nsd, b_mk, HDon, null);
        }
        
        /// <remarks/>
        public void ApiPHanhHDonAsync(string b_nsd, string b_mk, HDon HDon, object userState) {
            if ((this.ApiPHanhHDonOperationCompleted == null)) {
                this.ApiPHanhHDonOperationCompleted = new System.Threading.SendOrPostCallback(this.OnApiPHanhHDonOperationCompleted);
            }
            this.InvokeAsync("ApiPHanhHDon", new object[] {
                        b_nsd,
                        b_mk,
                        HDon}, this.ApiPHanhHDonOperationCompleted, userState);
        }
        
        private void OnApiPHanhHDonOperationCompleted(object arg) {
            if ((this.ApiPHanhHDonCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ApiPHanhHDonCompleted(this, new ApiPHanhHDonCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://microsoft.com/webservices/ApiPHanhHDonKSo", RequestNamespace="http://microsoft.com/webservices/", ResponseNamespace="http://microsoft.com/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ResponseMes ApiPHanhHDonKSo(string b_nsd, string b_mk, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] HDon HDon) {
            object[] results = this.Invoke("ApiPHanhHDonKSo", new object[] {
                        b_nsd,
                        b_mk,
                        HDon});
            return ((ResponseMes)(results[0]));
        }
        
        /// <remarks/>
        public void ApiPHanhHDonKSoAsync(string b_nsd, string b_mk, HDon HDon) {
            this.ApiPHanhHDonKSoAsync(b_nsd, b_mk, HDon, null);
        }
        
        /// <remarks/>
        public void ApiPHanhHDonKSoAsync(string b_nsd, string b_mk, HDon HDon, object userState) {
            if ((this.ApiPHanhHDonKSoOperationCompleted == null)) {
                this.ApiPHanhHDonKSoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnApiPHanhHDonKSoOperationCompleted);
            }
            this.InvokeAsync("ApiPHanhHDonKSo", new object[] {
                        b_nsd,
                        b_mk,
                        HDon}, this.ApiPHanhHDonKSoOperationCompleted, userState);
        }
        
        private void OnApiPHanhHDonKSoOperationCompleted(object arg) {
            if ((this.ApiPHanhHDonKSoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ApiPHanhHDonKSoCompleted(this, new ApiPHanhHDonKSoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://microsoft.com/webservices/ApiHuyHDon", RequestNamespace="http://microsoft.com/webservices/", ResponseNamespace="http://microsoft.com/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ApiHuyHDon(string b_nsd, string b_mk, string b_KeyHDon) {
            object[] results = this.Invoke("ApiHuyHDon", new object[] {
                        b_nsd,
                        b_mk,
                        b_KeyHDon});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ApiHuyHDonAsync(string b_nsd, string b_mk, string b_KeyHDon) {
            this.ApiHuyHDonAsync(b_nsd, b_mk, b_KeyHDon, null);
        }
        
        /// <remarks/>
        public void ApiHuyHDonAsync(string b_nsd, string b_mk, string b_KeyHDon, object userState) {
            if ((this.ApiHuyHDonOperationCompleted == null)) {
                this.ApiHuyHDonOperationCompleted = new System.Threading.SendOrPostCallback(this.OnApiHuyHDonOperationCompleted);
            }
            this.InvokeAsync("ApiHuyHDon", new object[] {
                        b_nsd,
                        b_mk,
                        b_KeyHDon}, this.ApiHuyHDonOperationCompleted, userState);
        }
        
        private void OnApiHuyHDonOperationCompleted(object arg) {
            if ((this.ApiHuyHDonCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ApiHuyHDonCompleted(this, new ApiHuyHDonCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://microsoft.com/webservices/ApiKyHDon", RequestNamespace="http://microsoft.com/webservices/", ResponseNamespace="http://microsoft.com/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ApiKyHDon(string b_nsd, string b_mk, string b_KeyHDon) {
            object[] results = this.Invoke("ApiKyHDon", new object[] {
                        b_nsd,
                        b_mk,
                        b_KeyHDon});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ApiKyHDonAsync(string b_nsd, string b_mk, string b_KeyHDon) {
            this.ApiKyHDonAsync(b_nsd, b_mk, b_KeyHDon, null);
        }
        
        /// <remarks/>
        public void ApiKyHDonAsync(string b_nsd, string b_mk, string b_KeyHDon, object userState) {
            if ((this.ApiKyHDonOperationCompleted == null)) {
                this.ApiKyHDonOperationCompleted = new System.Threading.SendOrPostCallback(this.OnApiKyHDonOperationCompleted);
            }
            this.InvokeAsync("ApiKyHDon", new object[] {
                        b_nsd,
                        b_mk,
                        b_KeyHDon}, this.ApiKyHDonOperationCompleted, userState);
        }
        
        private void OnApiKyHDonOperationCompleted(object arg) {
            if ((this.ApiKyHDonCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ApiKyHDonCompleted(this, new ApiKyHDonCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://microsoft.com/webservices/ApiInHoadon", RequestNamespace="http://microsoft.com/webservices/", ResponseNamespace="http://microsoft.com/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ApiInHoadon(string b_nsd, string b_mk, string b_KeyHDon) {
            object[] results = this.Invoke("ApiInHoadon", new object[] {
                        b_nsd,
                        b_mk,
                        b_KeyHDon});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ApiInHoadonAsync(string b_nsd, string b_mk, string b_KeyHDon) {
            this.ApiInHoadonAsync(b_nsd, b_mk, b_KeyHDon, null);
        }
        
        /// <remarks/>
        public void ApiInHoadonAsync(string b_nsd, string b_mk, string b_KeyHDon, object userState) {
            if ((this.ApiInHoadonOperationCompleted == null)) {
                this.ApiInHoadonOperationCompleted = new System.Threading.SendOrPostCallback(this.OnApiInHoadonOperationCompleted);
            }
            this.InvokeAsync("ApiInHoadon", new object[] {
                        b_nsd,
                        b_mk,
                        b_KeyHDon}, this.ApiInHoadonOperationCompleted, userState);
        }
        
        private void OnApiInHoadonOperationCompleted(object arg) {
            if ((this.ApiInHoadonCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ApiInHoadonCompleted(this, new ApiInHoadonCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://microsoft.com/webservices/ApiLayCTietHDon", RequestNamespace="http://microsoft.com/webservices/", ResponseNamespace="http://microsoft.com/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ApiLayCTietHDon(string b_nsd, string b_mk, string b_KeyHDon) {
            object[] results = this.Invoke("ApiLayCTietHDon", new object[] {
                        b_nsd,
                        b_mk,
                        b_KeyHDon});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ApiLayCTietHDonAsync(string b_nsd, string b_mk, string b_KeyHDon) {
            this.ApiLayCTietHDonAsync(b_nsd, b_mk, b_KeyHDon, null);
        }
        
        /// <remarks/>
        public void ApiLayCTietHDonAsync(string b_nsd, string b_mk, string b_KeyHDon, object userState) {
            if ((this.ApiLayCTietHDonOperationCompleted == null)) {
                this.ApiLayCTietHDonOperationCompleted = new System.Threading.SendOrPostCallback(this.OnApiLayCTietHDonOperationCompleted);
            }
            this.InvokeAsync("ApiLayCTietHDon", new object[] {
                        b_nsd,
                        b_mk,
                        b_KeyHDon}, this.ApiLayCTietHDonOperationCompleted, userState);
        }
        
        private void OnApiLayCTietHDonOperationCompleted(object arg) {
            if ((this.ApiLayCTietHDonCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ApiLayCTietHDonCompleted(this, new ApiLayCTietHDonCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://microsoft.com/webservices/ApiLayTTinMSKHHDon", RequestNamespace="http://microsoft.com/webservices/", ResponseNamespace="http://microsoft.com/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ApiLayTTinMSKHHDon(string b_nsd, string b_mk, string b_loai, double b_ngayph) {
            object[] results = this.Invoke("ApiLayTTinMSKHHDon", new object[] {
                        b_nsd,
                        b_mk,
                        b_loai,
                        b_ngayph});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ApiLayTTinMSKHHDonAsync(string b_nsd, string b_mk, string b_loai, double b_ngayph) {
            this.ApiLayTTinMSKHHDonAsync(b_nsd, b_mk, b_loai, b_ngayph, null);
        }
        
        /// <remarks/>
        public void ApiLayTTinMSKHHDonAsync(string b_nsd, string b_mk, string b_loai, double b_ngayph, object userState) {
            if ((this.ApiLayTTinMSKHHDonOperationCompleted == null)) {
                this.ApiLayTTinMSKHHDonOperationCompleted = new System.Threading.SendOrPostCallback(this.OnApiLayTTinMSKHHDonOperationCompleted);
            }
            this.InvokeAsync("ApiLayTTinMSKHHDon", new object[] {
                        b_nsd,
                        b_mk,
                        b_loai,
                        b_ngayph}, this.ApiLayTTinMSKHHDonOperationCompleted, userState);
        }
        
        private void OnApiLayTTinMSKHHDonOperationCompleted(object arg) {
            if ((this.ApiLayTTinMSKHHDonCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ApiLayTTinMSKHHDonCompleted(this, new ApiLayTTinMSKHHDonCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class HDon {
        
        private DLHDon dLHDonField;
        
        private TTCQT tTCQTField;
        
        private DSCKS dSCKSField;
        
        /// <remarks/>
        public DLHDon DLHDon {
            get {
                return this.dLHDonField;
            }
            set {
                this.dLHDonField = value;
            }
        }
        
        /// <remarks/>
        public TTCQT TTCQT {
            get {
                return this.tTCQTField;
            }
            set {
                this.tTCQTField = value;
            }
        }
        
        /// <remarks/>
        public DSCKS DSCKS {
            get {
                return this.dSCKSField;
            }
            set {
                this.dSCKSField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class DLHDon {
        
        private string keyField;
        
        private string keyOldField;
        
        private decimal idField;
        
        private TTChung tTChungField;
        
        private NDHDon nDHDonField;
        
        private TTin[] tTKhacField;
        
        /// <remarks/>
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public string KeyOld {
            get {
                return this.keyOldField;
            }
            set {
                this.keyOldField = value;
            }
        }
        
        /// <remarks/>
        public decimal id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public TTChung TTChung {
            get {
                return this.tTChungField;
            }
            set {
                this.tTChungField = value;
            }
        }
        
        /// <remarks/>
        public NDHDon NDHDon {
            get {
                return this.nDHDonField;
            }
            set {
                this.nDHDonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public TTin[] TTKhac {
            get {
                return this.tTKhacField;
            }
            set {
                this.tTKhacField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class TTChung {
        
        private string pBanField;
        
        private string tHDonField;
        
        private string kHMSHDonField;
        
        private string kHHDonField;
        
        private string sHDonField;
        
        private string tDLapField;
        
        private string tChatField;
        
        private string dVTTeField;
        
        private double tGiaField;
        
        private string hTHDBTTheField;
        
        private string tDLHDBTTheField;
        
        private string kHMSHDBTTheField;
        
        private string kHHDBTTheField;
        
        private string sHDBTTheField;
        
        private TTin[] tTKhacField;
        
        /// <remarks/>
        public string PBan {
            get {
                return this.pBanField;
            }
            set {
                this.pBanField = value;
            }
        }
        
        /// <remarks/>
        public string THDon {
            get {
                return this.tHDonField;
            }
            set {
                this.tHDonField = value;
            }
        }
        
        /// <remarks/>
        public string KHMSHDon {
            get {
                return this.kHMSHDonField;
            }
            set {
                this.kHMSHDonField = value;
            }
        }
        
        /// <remarks/>
        public string KHHDon {
            get {
                return this.kHHDonField;
            }
            set {
                this.kHHDonField = value;
            }
        }
        
        /// <remarks/>
        public string SHDon {
            get {
                return this.sHDonField;
            }
            set {
                this.sHDonField = value;
            }
        }
        
        /// <remarks/>
        public string TDLap {
            get {
                return this.tDLapField;
            }
            set {
                this.tDLapField = value;
            }
        }
        
        /// <remarks/>
        public string TChat {
            get {
                return this.tChatField;
            }
            set {
                this.tChatField = value;
            }
        }
        
        /// <remarks/>
        public string DVTTe {
            get {
                return this.dVTTeField;
            }
            set {
                this.dVTTeField = value;
            }
        }
        
        /// <remarks/>
        public double TGia {
            get {
                return this.tGiaField;
            }
            set {
                this.tGiaField = value;
            }
        }
        
        /// <remarks/>
        public string HTHDBTThe {
            get {
                return this.hTHDBTTheField;
            }
            set {
                this.hTHDBTTheField = value;
            }
        }
        
        /// <remarks/>
        public string TDLHDBTThe {
            get {
                return this.tDLHDBTTheField;
            }
            set {
                this.tDLHDBTTheField = value;
            }
        }
        
        /// <remarks/>
        public string KHMSHDBTThe {
            get {
                return this.kHMSHDBTTheField;
            }
            set {
                this.kHMSHDBTTheField = value;
            }
        }
        
        /// <remarks/>
        public string KHHDBTThe {
            get {
                return this.kHHDBTTheField;
            }
            set {
                this.kHHDBTTheField = value;
            }
        }
        
        /// <remarks/>
        public string SHDBTThe {
            get {
                return this.sHDBTTheField;
            }
            set {
                this.sHDBTTheField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public TTin[] TTKhac {
            get {
                return this.tTKhacField;
            }
            set {
                this.tTKhacField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class TTin {
        
        private string tTruongField;
        
        private string kDLieuField;
        
        private string dLieuField;
        
        /// <remarks/>
        public string TTruong {
            get {
                return this.tTruongField;
            }
            set {
                this.tTruongField = value;
            }
        }
        
        /// <remarks/>
        public string KDLieu {
            get {
                return this.kDLieuField;
            }
            set {
                this.kDLieuField = value;
            }
        }
        
        /// <remarks/>
        public string DLieu {
            get {
                return this.dLieuField;
            }
            set {
                this.dLieuField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class ResponseMes {
        
        private string returnCodeField;
        
        private string errorMessageField;
        
        private string keyField;
        
        private string kHMSHDonField;
        
        private string kHHDonField;
        
        private string sHDonField;
        
        private string mTCuuField;
        
        private string pdfBase64Field;
        
        private string exceptionLogField;
        
        /// <remarks/>
        public string ReturnCode {
            get {
                return this.returnCodeField;
            }
            set {
                this.returnCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public string KHMSHDon {
            get {
                return this.kHMSHDonField;
            }
            set {
                this.kHMSHDonField = value;
            }
        }
        
        /// <remarks/>
        public string KHHDon {
            get {
                return this.kHHDonField;
            }
            set {
                this.kHHDonField = value;
            }
        }
        
        /// <remarks/>
        public string SHDon {
            get {
                return this.sHDonField;
            }
            set {
                this.sHDonField = value;
            }
        }
        
        /// <remarks/>
        public string MTCuu {
            get {
                return this.mTCuuField;
            }
            set {
                this.mTCuuField = value;
            }
        }
        
        /// <remarks/>
        public string PdfBase64 {
            get {
                return this.pdfBase64Field;
            }
            set {
                this.pdfBase64Field = value;
            }
        }
        
        /// <remarks/>
        public string ExceptionLog {
            get {
                return this.exceptionLogField;
            }
            set {
                this.exceptionLogField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class DSCKS {
        
        private Signature nBanField;
        
        private Signature nMuaField;
        
        private Signature tCTField;
        
        private Signature cCKSKhacField;
        
        /// <remarks/>
        public Signature NBan {
            get {
                return this.nBanField;
            }
            set {
                this.nBanField = value;
            }
        }
        
        /// <remarks/>
        public Signature NMua {
            get {
                return this.nMuaField;
            }
            set {
                this.nMuaField = value;
            }
        }
        
        /// <remarks/>
        public Signature TCT {
            get {
                return this.tCTField;
            }
            set {
                this.tCTField = value;
            }
        }
        
        /// <remarks/>
        public Signature CCKSKhac {
            get {
                return this.cCKSKhacField;
            }
            set {
                this.cCKSKhacField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class Signature {
        
        private string signature1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Signature")]
        public string Signature1 {
            get {
                return this.signature1Field;
            }
            set {
                this.signature1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class TTCQT {
        
        private string mCCQTField;
        
        private string mSTNBanField;
        
        private string kHMSHDonField;
        
        private string kHHDonField;
        
        private string sHDonField;
        
        private string tDLapField;
        
        private Signature tCTField;
        
        /// <remarks/>
        public string MCCQT {
            get {
                return this.mCCQTField;
            }
            set {
                this.mCCQTField = value;
            }
        }
        
        /// <remarks/>
        public string MSTNBan {
            get {
                return this.mSTNBanField;
            }
            set {
                this.mSTNBanField = value;
            }
        }
        
        /// <remarks/>
        public string KHMSHDon {
            get {
                return this.kHMSHDonField;
            }
            set {
                this.kHMSHDonField = value;
            }
        }
        
        /// <remarks/>
        public string KHHDon {
            get {
                return this.kHHDonField;
            }
            set {
                this.kHHDonField = value;
            }
        }
        
        /// <remarks/>
        public string SHDon {
            get {
                return this.sHDonField;
            }
            set {
                this.sHDonField = value;
            }
        }
        
        /// <remarks/>
        public string TDLap {
            get {
                return this.tDLapField;
            }
            set {
                this.tDLapField = value;
            }
        }
        
        /// <remarks/>
        public Signature TCT {
            get {
                return this.tCTField;
            }
            set {
                this.tCTField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class LTSuat {
        
        private string tSuatField;
        
        private decimal tThueField;
        
        private decimal thTienField;
        
        /// <remarks/>
        public string TSuat {
            get {
                return this.tSuatField;
            }
            set {
                this.tSuatField = value;
            }
        }
        
        /// <remarks/>
        public decimal TThue {
            get {
                return this.tThueField;
            }
            set {
                this.tThueField = value;
            }
        }
        
        /// <remarks/>
        public decimal ThTien {
            get {
                return this.thTienField;
            }
            set {
                this.thTienField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class TToan {
        
        private decimal tgTCThueField;
        
        private decimal tgTThueField;
        
        private decimal tgTHHDVuField;
        
        private decimal tLPhiField;
        
        private decimal tPhiField;
        
        private decimal tTCKTMaiField;
        
        private decimal tgTTTBSoField;
        
        private string tgTTTBChuField;
        
        private LTSuat[] tHTTLTSuatField;
        
        private TTin[] tTKhacField;
        
        /// <remarks/>
        public decimal TgTCThue {
            get {
                return this.tgTCThueField;
            }
            set {
                this.tgTCThueField = value;
            }
        }
        
        /// <remarks/>
        public decimal TgTThue {
            get {
                return this.tgTThueField;
            }
            set {
                this.tgTThueField = value;
            }
        }
        
        /// <remarks/>
        public decimal TgTHHDVu {
            get {
                return this.tgTHHDVuField;
            }
            set {
                this.tgTHHDVuField = value;
            }
        }
        
        /// <remarks/>
        public decimal TLPhi {
            get {
                return this.tLPhiField;
            }
            set {
                this.tLPhiField = value;
            }
        }
        
        /// <remarks/>
        public decimal TPhi {
            get {
                return this.tPhiField;
            }
            set {
                this.tPhiField = value;
            }
        }
        
        /// <remarks/>
        public decimal TTCKTMai {
            get {
                return this.tTCKTMaiField;
            }
            set {
                this.tTCKTMaiField = value;
            }
        }
        
        /// <remarks/>
        public decimal TgTTTBSo {
            get {
                return this.tgTTTBSoField;
            }
            set {
                this.tgTTTBSoField = value;
            }
        }
        
        /// <remarks/>
        public string TgTTTBChu {
            get {
                return this.tgTTTBChuField;
            }
            set {
                this.tgTTTBChuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("THTTLTSuat")]
        public LTSuat[] THTTLTSuat {
            get {
                return this.tHTTLTSuatField;
            }
            set {
                this.tHTTLTSuatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public TTin[] TTKhac {
            get {
                return this.tTKhacField;
            }
            set {
                this.tTKhacField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class HHDVu {
        
        private int tChatField;
        
        private int sTTField;
        
        private string maField;
        
        private string tenField;
        
        private string dVTinhField;
        
        private decimal sLuongField;
        
        private decimal dGiaField;
        
        private decimal tLCKhauField;
        
        private decimal sTCKhauField;
        
        private decimal thTienField;
        
        private string tSuatField;
        
        private decimal tThueField;
        
        private TTin[] tTKhacField;
        
        /// <remarks/>
        public int TChat {
            get {
                return this.tChatField;
            }
            set {
                this.tChatField = value;
            }
        }
        
        /// <remarks/>
        public int STT {
            get {
                return this.sTTField;
            }
            set {
                this.sTTField = value;
            }
        }
        
        /// <remarks/>
        public string Ma {
            get {
                return this.maField;
            }
            set {
                this.maField = value;
            }
        }
        
        /// <remarks/>
        public string Ten {
            get {
                return this.tenField;
            }
            set {
                this.tenField = value;
            }
        }
        
        /// <remarks/>
        public string DVTinh {
            get {
                return this.dVTinhField;
            }
            set {
                this.dVTinhField = value;
            }
        }
        
        /// <remarks/>
        public decimal SLuong {
            get {
                return this.sLuongField;
            }
            set {
                this.sLuongField = value;
            }
        }
        
        /// <remarks/>
        public decimal DGia {
            get {
                return this.dGiaField;
            }
            set {
                this.dGiaField = value;
            }
        }
        
        /// <remarks/>
        public decimal TLCKhau {
            get {
                return this.tLCKhauField;
            }
            set {
                this.tLCKhauField = value;
            }
        }
        
        /// <remarks/>
        public decimal STCKhau {
            get {
                return this.sTCKhauField;
            }
            set {
                this.sTCKhauField = value;
            }
        }
        
        /// <remarks/>
        public decimal ThTien {
            get {
                return this.thTienField;
            }
            set {
                this.thTienField = value;
            }
        }
        
        /// <remarks/>
        public string TSuat {
            get {
                return this.tSuatField;
            }
            set {
                this.tSuatField = value;
            }
        }
        
        /// <remarks/>
        public decimal TThue {
            get {
                return this.tThueField;
            }
            set {
                this.tThueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public TTin[] TTKhac {
            get {
                return this.tTKhacField;
            }
            set {
                this.tTKhacField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class NMua {
        
        private string tenField;
        
        private string mSTField;
        
        private string dChiField;
        
        private TTin[] tTKhacField;
        
        /// <remarks/>
        public string Ten {
            get {
                return this.tenField;
            }
            set {
                this.tenField = value;
            }
        }
        
        /// <remarks/>
        public string MST {
            get {
                return this.mSTField;
            }
            set {
                this.mSTField = value;
            }
        }
        
        /// <remarks/>
        public string DChi {
            get {
                return this.dChiField;
            }
            set {
                this.dChiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public TTin[] TTKhac {
            get {
                return this.tTKhacField;
            }
            set {
                this.tTKhacField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class NBan {
        
        private string tenField;
        
        private string mSTField;
        
        private string dChiField;
        
        /// <remarks/>
        public string Ten {
            get {
                return this.tenField;
            }
            set {
                this.tenField = value;
            }
        }
        
        /// <remarks/>
        public string MST {
            get {
                return this.mSTField;
            }
            set {
                this.mSTField = value;
            }
        }
        
        /// <remarks/>
        public string DChi {
            get {
                return this.dChiField;
            }
            set {
                this.dChiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://microsoft.com/webservices/")]
    public partial class NDHDon {
        
        private NBan nBanField;
        
        private NMua nMuaField;
        
        private HHDVu[] dSHHDVuField;
        
        private TToan tToanField;
        
        /// <remarks/>
        public NBan NBan {
            get {
                return this.nBanField;
            }
            set {
                this.nBanField = value;
            }
        }
        
        /// <remarks/>
        public NMua NMua {
            get {
                return this.nMuaField;
            }
            set {
                this.nMuaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public HHDVu[] DSHHDVu {
            get {
                return this.dSHHDVuField;
            }
            set {
                this.dSHHDVuField = value;
            }
        }
        
        /// <remarks/>
        public TToan TToan {
            get {
                return this.tToanField;
            }
            set {
                this.tToanField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ApiPHanhHDonCompletedEventHandler(object sender, ApiPHanhHDonCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ApiPHanhHDonCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ApiPHanhHDonCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ApiPHanhHDonKSoCompletedEventHandler(object sender, ApiPHanhHDonKSoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ApiPHanhHDonKSoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ApiPHanhHDonKSoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResponseMes Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResponseMes)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ApiHuyHDonCompletedEventHandler(object sender, ApiHuyHDonCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ApiHuyHDonCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ApiHuyHDonCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ApiKyHDonCompletedEventHandler(object sender, ApiKyHDonCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ApiKyHDonCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ApiKyHDonCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ApiInHoadonCompletedEventHandler(object sender, ApiInHoadonCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ApiInHoadonCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ApiInHoadonCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ApiLayCTietHDonCompletedEventHandler(object sender, ApiLayCTietHDonCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ApiLayCTietHDonCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ApiLayCTietHDonCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ApiLayTTinMSKHHDonCompletedEventHandler(object sender, ApiLayTTinMSKHHDonCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ApiLayTTinMSKHHDonCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ApiLayTTinMSKHHDonCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591